---
- hosts: webservers
  become: yes
  tasks: 
    - name: Install Apache
      package:
        name: apache2
        state: latest
    - name: Delete index.html if it exists
      file:
        path: /var/www/html/index.html
        state: absent     
    - name: git checkout the website
      git:
        dest: /var/www/html
        repo: https://github.com/lu-vumc-devops/lu-vumc-devops.superwebpage.git
        force: yes
    - name: Start theApache service
      service:
         name: apache2
         state: started 
    - name: Open the ssh firewall ports
      ufw:
        rule: allow
        name: OpenSSH
        src: '{{ item }}'
      with_items:
         - 192.168.0.0/16
         - 89.254.128.0/18
    - name: Open the http firewall ports
      ufw:
        rule: allow
        port: 80
        state: enabled
